// Copyright June Rhodes. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#include "OnlineUserPrivilege.generated.h"

UENUM(BlueprintType, Meta = (ScriptName = "EUserPrivileges"))
enum class EOnlineUserPrivilege : uint8
{
    /** Whether the user can play at all, online or offline - may be age restricted */
    CanPlay,
    /** Whether the user can play in online modes */
    CanPlayOnline,
    /** Whether the user can use voice and text chat */
    CanCommunicateOnline,
    /** Whether the user can use content generated by other users */
    CanUseUserGeneratedContent,
    /** Whether the user can ever participate in cross-play due to age restrictions */
    CanUserCrossPlay
};